version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: segmentation-postgres
    environment:
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops
      POSTGRES_DB: segmentation
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: segmentation-mlflow
    depends_on:
      - postgres
    command: >
      bash -c "pip install psycopg2-binary &&
      chmod -R 777 /mlflow &&
      mlflow server
      --backend-store-uri postgresql://mlops:mlops@postgres:5432/mlflow
      --default-artifact-root mlflow-artifacts:/artifacts
      --serve-artifacts
      --artifacts-destination /mlflow/artifacts
      --host 0.0.0.0
      --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/mlflow

  airflow:
    image: apache/airflow:2.7.3
    container_name: segmentation-airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlops:mlops@postgres:5432/segmentation
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      PYTHONPATH: /opt/airflow
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
      - mlflow_artifacts:/mlflow
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install psycopg2-binary pandas sqlalchemy scikit-learn==1.3.2 mlflow &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true &&
      pkill -f 'airflow webserver' || true &&
      rm -f /opt/airflow/airflow-webserver.pid &&
      airflow webserver --port 8080 & airflow scheduler"

volumes:
  pgdata:
  mlflow_artifacts:
